from __future__ import annotations

from typing import NamedTuple
from enum import IntEnum
from BaseClasses import Item, ItemClassification as IC
from .Enums import Items


class MM2ShipItem(Item):
    game = "2 Ship 2 Harkinian (MM)"


class ItemType(IntEnum):
    none = 0
    song = 1
    magic = 2  # things that cost magic


class MM2ShipItemData(NamedTuple):
    # None means it's just here for the data, and won't be added to the datapackage
    item_id: int | None
    classification: IC = IC.progression
    quantity_in_item_pool: int = 0
    item_type: int = ItemType.none
    # MM: no child/adult split, fields kept for SoH-compat style
    child_only: bool = False
    adult_only: bool = False
    item_groups: list[str] = []  # for item_name_groups


item_data_table: dict[Items, MM2ShipItemData] = {
    Items.ABILITY_SWIM: MM2ShipItemData(1, IC.progression, 1),
    Items.ARROW_FIRE: MM2ShipItemData(2, IC.progression, 1),
    Items.ARROW_ICE: MM2ShipItemData(3, IC.progression, 1),
    Items.ARROW_LIGHT: MM2ShipItemData(4, IC.progression, 1),
    Items.ARROWS_10: MM2ShipItemData(5, IC.filler, 1),
    Items.ARROWS_30: MM2ShipItemData(6, IC.filler, 1),
    Items.ARROWS_50: MM2ShipItemData(7, IC.filler, 1),
    Items.BLUE_POTION_REFILL: MM2ShipItemData(8, IC.filler, 1),
    Items.BOMB_BAG_20: MM2ShipItemData(9, IC.progression, 1),
    Items.BOMB_BAG_30: MM2ShipItemData(10, IC.useful, 1),
    Items.BOMB_BAG_40: MM2ShipItemData(11, IC.useful, 1),
    Items.BOMBCHU_10: MM2ShipItemData(12, IC.filler, 1),
    Items.BOMBCHU_5: MM2ShipItemData(13, IC.filler, 1),
    Items.BOMBCHU: MM2ShipItemData(14, IC.filler, 1),
    Items.BOMBERS_NOTEBOOK: MM2ShipItemData(15, IC.useful, 1),
    Items.BOMBS_10: MM2ShipItemData(16, IC.filler, 1),
    Items.BOMBS_5: MM2ShipItemData(17, IC.filler, 1),
    Items.BOTTLE_CHATEAU_ROMANI: MM2ShipItemData(18, IC.progression, 1),
    Items.BOTTLE_EMPTY: MM2ShipItemData(19, IC.progression, 1),
    Items.BOTTLE_GOLD_DUST: MM2ShipItemData(20, IC.progression, 1),
    Items.BOTTLE_MILK: MM2ShipItemData(21, IC.progression, 1),
    Items.BOTTLE_RED_POTION: MM2ShipItemData(22, IC.progression, 1),
    Items.BOW: MM2ShipItemData(23, IC.progression, 1),
    Items.CHATEAU_ROMANI_REFILL: MM2ShipItemData(24, IC.filler, 1),
    Items.CLOCK_TOWN_STRAY_FAIRY: MM2ShipItemData(25, IC.progression, 1),
    Items.DEED_LAND: MM2ShipItemData(26, IC.progression, 1),
    Items.DEED_MOUNTAIN: MM2ShipItemData(27, IC.progression, 1),
    Items.DEED_OCEAN: MM2ShipItemData(28, IC.progression, 1),
    Items.DEED_SWAMP: MM2ShipItemData(29, IC.progression, 1),
    Items.DEKU_NUT: MM2ShipItemData(30, IC.filler, 1),
    Items.DEKU_NUTS_10: MM2ShipItemData(31, IC.filler, 1),
    Items.DEKU_NUTS_5: MM2ShipItemData(32, IC.filler, 1),
    Items.DEKU_STICK: MM2ShipItemData(33, IC.filler, 1),
    Items.DEKU_STICKS_5: MM2ShipItemData(34, IC.filler, 1),
    Items.DOUBLE_DEFENSE: MM2ShipItemData(35, IC.useful, 1),
    Items.DOUBLE_MAGIC: MM2ShipItemData(36, IC.useful, 1),
    Items.FAIRY_REFILL: MM2ShipItemData(37, IC.filler, 1),
    Items.FROG_BLUE: MM2ShipItemData(38, IC.progression, 1),
    Items.FROG_CYAN: MM2ShipItemData(39, IC.progression, 1),
    Items.FROG_PINK: MM2ShipItemData(40, IC.progression, 1),
    Items.FROG_WHITE: MM2ShipItemData(41, IC.progression, 1),
    Items.GOLD_DUST_REFILL: MM2ShipItemData(42, IC.useful, 1),
    Items.GREAT_BAY_BOSS_KEY: MM2ShipItemData(43, IC.progression, 1),
    Items.GREAT_BAY_COMPASS: MM2ShipItemData(44, IC.useful, 1),
    Items.GREAT_BAY_MAP: MM2ShipItemData(45, IC.useful, 1),
    Items.GREAT_BAY_SMALL_KEY: MM2ShipItemData(46, IC.progression, 1),
    Items.GREAT_BAY_STRAY_FAIRY: MM2ShipItemData(47, IC.useful, 1),
    Items.GREAT_FAIRY_SWORD: MM2ShipItemData(48, IC.useful, 1),
    Items.GREAT_SPIN_ATTACK: MM2ShipItemData(49, IC.useful, 1),
    Items.GREEN_POTION_REFILL: MM2ShipItemData(50, IC.filler, 1),
    Items.GS_TOKEN_OCEAN: MM2ShipItemData(51, IC.useful, 1),
    Items.GS_TOKEN_SWAMP: MM2ShipItemData(52, IC.useful, 1),
    Items.HEART_CONTAINER: MM2ShipItemData(53, IC.useful, 1),
    Items.HEART_PIECE: MM2ShipItemData(54, IC.useful, 1),
    Items.HOOKSHOT: MM2ShipItemData(55, IC.progression, 1),
    Items.JUNK: MM2ShipItemData(56, IC.filler, 1),
    Items.LENS: MM2ShipItemData(57, IC.progression, 1),
    Items.LETTER_TO_KAFEI: MM2ShipItemData(58, IC.progression, 1),
    Items.LETTER_TO_MAMA: MM2ShipItemData(59, IC.progression, 1),
    Items.MAGIC_BEAN: MM2ShipItemData(60, IC.useful, 1),
    Items.MAGIC_JAR_BIG: MM2ShipItemData(61, IC.filler, 1),
    Items.MAGIC_JAR_SMALL: MM2ShipItemData(62, IC.filler, 1),
    Items.MASK_ALL_NIGHT: MM2ShipItemData(63, IC.progression, 1),
    Items.MASK_BLAST: MM2ShipItemData(64, IC.progression, 1),
    Items.MASK_BREMEN: MM2ShipItemData(65, IC.progression, 1),
    Items.MASK_BUNNY: MM2ShipItemData(66, IC.progression, 1),
    Items.MASK_CAPTAIN: MM2ShipItemData(67, IC.progression, 1),
    Items.MASK_CIRCUS_LEADER: MM2ShipItemData(68, IC.progression, 1),
    Items.MASK_COUPLE: MM2ShipItemData(69, IC.progression, 1),
    Items.MASK_DEKU: MM2ShipItemData(70, IC.progression, 1),
    Items.MASK_DON_GERO: MM2ShipItemData(71, IC.progression, 1),
    Items.MASK_FIERCE_DEITY: MM2ShipItemData(72, IC.progression, 1),
    Items.MASK_GARO: MM2ShipItemData(73, IC.progression, 1),
    Items.MASK_GIANT: MM2ShipItemData(74, IC.progression, 1),
    Items.MASK_GIBDO: MM2ShipItemData(75, IC.progression, 1),
    Items.MASK_GORON: MM2ShipItemData(76, IC.progression, 1),
    Items.MASK_GREAT_FAIRY: MM2ShipItemData(77, IC.progression, 1),
    Items.MASK_KAFEIS_MASK: MM2ShipItemData(78, IC.progression, 1),
    Items.MASK_KAMARO: MM2ShipItemData(79, IC.progression, 1),
    Items.MASK_KEATON: MM2ShipItemData(80, IC.progression, 1),
    Items.MASK_POSTMAN: MM2ShipItemData(81, IC.progression, 1),
    Items.MASK_ROMANI: MM2ShipItemData(82, IC.progression, 1),
    Items.MASK_SCENTS: MM2ShipItemData(83, IC.progression, 1),
    Items.MASK_STONE: MM2ShipItemData(84, IC.progression, 1),
    Items.MASK_TRUTH: MM2ShipItemData(85, IC.progression, 1),
    Items.MASK_ZORA: MM2ShipItemData(86, IC.progression, 1),
    Items.MILK_REFILL: MM2ShipItemData(87, IC.filler, 1),
    Items.MOONS_TEAR: MM2ShipItemData(88, IC.progression, 1),
    Items.MUSHROOM: MM2ShipItemData(89, IC.progression, 1),
    Items.NONE: MM2ShipItemData(90, IC.filler, 1),
    Items.OCARINA_BUTTON_A: MM2ShipItemData(91, IC.progression, 1),
    Items.OCARINA_BUTTON_C_DOWN: MM2ShipItemData(92, IC.progression, 1),
    Items.OCARINA_BUTTON_C_RIGHT: MM2ShipItemData(93, IC.progression, 1),
    Items.OCARINA_BUTTON_C_LEFT: MM2ShipItemData(94, IC.progression, 1),
    Items.OCARINA_BUTTON_C_UP: MM2ShipItemData(95, IC.progression, 1),
    Items.OCARINA: MM2ShipItemData(96, IC.progression, 1),
    Items.OWL_CLOCK_TOWN_SOUTH: MM2ShipItemData(97, IC.useful, 1),
    Items.OWL_GREAT_BAY_COAST: MM2ShipItemData(98, IC.useful, 1),
    Items.OWL_IKANA_CANYON: MM2ShipItemData(99, IC.useful, 1),
    Items.OWL_MILK_ROAD: MM2ShipItemData(100, IC.useful, 1),
    Items.OWL_MOUNTAIN_VILLAGE: MM2ShipItemData(101, IC.useful, 1),
    Items.OWL_SNOWHEAD: MM2ShipItemData(102, IC.useful, 1),
    Items.OWL_SOUTHERN_SWAMP: MM2ShipItemData(103, IC.useful, 1),
    Items.OWL_STONE_TOWER: MM2ShipItemData(104, IC.useful, 1),
    Items.OWL_WOODFALL: MM2ShipItemData(105, IC.useful, 1),
    Items.OWL_ZORA_CAPE: MM2ShipItemData(106, IC.useful, 1),
    Items.PENDANT_OF_MEMORIES: MM2ShipItemData(107, IC.progression, 1),
    Items.PICTOGRAPH_BOX: MM2ShipItemData(108, IC.progression, 1),
    Items.POWDER_KEG: MM2ShipItemData(109, IC.progression, 1),
    Items.PROGRESSIVE_BOMB_BAG: MM2ShipItemData(110, IC.progression, 1),
    Items.PROGRESSIVE_BOW: MM2ShipItemData(111, IC.progression, 1),
    Items.PROGRESSIVE_LULLABY: MM2ShipItemData(112, IC.progression, 1),
    Items.PROGRESSIVE_MAGIC: MM2ShipItemData(113, IC.progression, 1),
    Items.PROGRESSIVE_SWORD: MM2ShipItemData(114, IC.progression, 1),
    Items.PROGRESSIVE_WALLET: MM2ShipItemData(115, IC.progression, 1),
    Items.QUIVER_40: MM2ShipItemData(116, IC.useful, 1),
    Items.QUIVER_50: MM2ShipItemData(117, IC.useful, 1),
    Items.RECOVERY_HEART: MM2ShipItemData(118, IC.filler, 1),
    Items.RED_POTION_REFILL: MM2ShipItemData(119, IC.filler, 1),
    Items.REMAINS_GOHT: MM2ShipItemData(120, IC.progression, 1),
    Items.REMAINS_GYORG: MM2ShipItemData(121, IC.progression, 1),
    Items.REMAINS_ODOLWA: MM2ShipItemData(122, IC.progression, 1),
    Items.REMAINS_TWINMOLD: MM2ShipItemData(123, IC.progression, 1),
    Items.ROOM_KEY: MM2ShipItemData(124, IC.progression, 1),
    Items.RUPEE_BLUE: MM2ShipItemData(125, IC.filler, 1),
    Items.RUPEE_GREEN: MM2ShipItemData(126, IC.filler, 1),
    Items.RUPEE_HUGE: MM2ShipItemData(127, IC.filler, 1),
    Items.RUPEE_PURPLE: MM2ShipItemData(128, IC.filler, 1),
    Items.RUPEE_RED: MM2ShipItemData(129, IC.filler, 1),
    Items.RUPEE_SILVER: MM2ShipItemData(130, IC.filler, 1),
    Items.SHIELD_HERO: MM2ShipItemData(131, IC.progression, 1),
    Items.SHIELD_MIRROR: MM2ShipItemData(132, IC.progression, 1),
    Items.SINGLE_MAGIC: MM2ShipItemData(133, IC.progression, 1),
    Items.SNOWHEAD_BOSS_KEY: MM2ShipItemData(134, IC.progression, 1),
    Items.SNOWHEAD_COMPASS: MM2ShipItemData(135, IC.useful, 1),
    Items.SNOWHEAD_MAP: MM2ShipItemData(136, IC.useful, 1),
    Items.SNOWHEAD_SMALL_KEY: MM2ShipItemData(137, IC.progression, 1),
    Items.SNOWHEAD_STRAY_FAIRY: MM2ShipItemData(138, IC.useful, 1),
    Items.SONG_DOUBLE_TIME: MM2ShipItemData(139, IC.progression, 1),
    Items.SONG_ELEGY: MM2ShipItemData(140, IC.progression, 1),
    Items.SONG_EPONA: MM2ShipItemData(141, IC.progression, 1),
    Items.SONG_HEALING: MM2ShipItemData(142, IC.progression, 1),
    Items.SONG_INVERTED_TIME: MM2ShipItemData(143, IC.progression, 1),
    Items.SONG_LULLABY_INTRO: MM2ShipItemData(144, IC.progression, 1),
    Items.SONG_LULLABY: MM2ShipItemData(145, IC.progression, 1),
    Items.SONG_NOVA: MM2ShipItemData(146, IC.progression, 1),
    Items.SONG_OATH: MM2ShipItemData(147, IC.progression, 1),
    Items.SONG_SARIA: MM2ShipItemData(148, IC.progression, 1),
    Items.SONG_SOARING: MM2ShipItemData(149, IC.progression, 1),
    Items.SONG_SONATA: MM2ShipItemData(150, IC.progression, 1),
    Items.SONG_STORMS: MM2ShipItemData(151, IC.progression, 1),
    Items.SONG_SUN: MM2ShipItemData(152, IC.progression, 1),
    Items.SONG_TIME: MM2ShipItemData(153, IC.progression, 1),
    Items.SOUL_BOSS_GOHT: MM2ShipItemData(154, IC.progression, 1),
    Items.SOUL_BOSS_GYORG: MM2ShipItemData(155, IC.progression, 1),
    Items.SOUL_BOSS_MAJORA: MM2ShipItemData(156, IC.progression, 1),
    Items.SOUL_BOSS_ODOLWA: MM2ShipItemData(157, IC.progression, 1),
    Items.SOUL_BOSS_TWINMOLD: MM2ShipItemData(158, IC.progression, 1),
    Items.SOUL_ENEMY_ALIEN: MM2ShipItemData(159, IC.progression, 1),
    Items.SOUL_ENEMY_ARMOS: MM2ShipItemData(160, IC.progression, 1),
    Items.SOUL_ENEMY_BAD_BAT: MM2ShipItemData(161, IC.progression, 1),
    Items.SOUL_ENEMY_BEAMOS: MM2ShipItemData(162, IC.progression, 1),
    Items.SOUL_ENEMY_BOE: MM2ShipItemData(163, IC.progression, 1),
    Items.SOUL_ENEMY_BUBBLE: MM2ShipItemData(164, IC.progression, 1),
    Items.SOUL_ENEMY_CAPTAIN_KEETA: MM2ShipItemData(165, IC.progression, 1),
    Items.SOUL_ENEMY_CHUCHU: MM2ShipItemData(166, IC.progression, 1),
    Items.SOUL_ENEMY_DEATH_ARMOS: MM2ShipItemData(167, IC.progression, 1),
    Items.SOUL_ENEMY_DEEP_PYTHON: MM2ShipItemData(168, IC.progression, 1),
    Items.SOUL_ENEMY_DEKU_BABA: MM2ShipItemData(169, IC.progression, 1),
    Items.SOUL_ENEMY_DEXIHAND: MM2ShipItemData(170, IC.progression, 1),
    Items.SOUL_ENEMY_DINOLFOS: MM2ShipItemData(171, IC.progression, 1),
    Items.SOUL_ENEMY_DODONGO: MM2ShipItemData(172, IC.progression, 1),
    Items.SOUL_ENEMY_DRAGONFLY: MM2ShipItemData(173, IC.progression, 1),
    Items.SOUL_ENEMY_EENO: MM2ShipItemData(174, IC.progression, 1),
    Items.SOUL_ENEMY_EYEGORE: MM2ShipItemData(175, IC.progression, 1),
    Items.SOUL_ENEMY_FREEZARD: MM2ShipItemData(176, IC.progression, 1),
    Items.SOUL_ENEMY_GARO: MM2ShipItemData(177, IC.progression, 1),
    Items.SOUL_ENEMY_GEKKO: MM2ShipItemData(178, IC.progression, 1),
    Items.SOUL_ENEMY_GIANT_BEE: MM2ShipItemData(179, IC.progression, 1),
    Items.SOUL_ENEMY_GOMESS: MM2ShipItemData(180, IC.progression, 1),
    Items.SOUL_ENEMY_GUAY: MM2ShipItemData(181, IC.progression, 1),
    Items.SOUL_ENEMY_HIPLOOP: MM2ShipItemData(182, IC.progression, 1),
    Items.SOUL_ENEMY_IGOS_DU_IKANA: MM2ShipItemData(183, IC.progression, 1),
    Items.SOUL_ENEMY_IRON_KNUCKLE: MM2ShipItemData(184, IC.progression, 1),
    Items.SOUL_ENEMY_KEESE: MM2ShipItemData(185, IC.progression, 1),
    Items.SOUL_ENEMY_LEEVER: MM2ShipItemData(186, IC.progression, 1),
    Items.SOUL_ENEMY_LIKE_LIKE: MM2ShipItemData(187, IC.progression, 1),
    Items.SOUL_ENEMY_MAD_SCRUB: MM2ShipItemData(188, IC.progression, 1),
    Items.SOUL_ENEMY_NEJIRON: MM2ShipItemData(189, IC.progression, 1),
    Items.SOUL_ENEMY_OCTOROK: MM2ShipItemData(190, IC.progression, 1),
    Items.SOUL_ENEMY_PEAHAT: MM2ShipItemData(191, IC.progression, 1),
    Items.SOUL_ENEMY_PIRATE: MM2ShipItemData(192, IC.progression, 1),
    Items.SOUL_ENEMY_POE: MM2ShipItemData(193, IC.progression, 1),
    Items.SOUL_ENEMY_REDEAD: MM2ShipItemData(194, IC.progression, 1),
    Items.SOUL_ENEMY_SHELLBLADE: MM2ShipItemData(195, IC.progression, 1),
    Items.SOUL_ENEMY_SKULLFISH: MM2ShipItemData(196, IC.progression, 1),
    Items.SOUL_ENEMY_SKULLTULA: MM2ShipItemData(197, IC.progression, 1),
    Items.SOUL_ENEMY_SNAPPER: MM2ShipItemData(198, IC.progression, 1),
    Items.SOUL_ENEMY_STALCHILD: MM2ShipItemData(199, IC.progression, 1),
    Items.SOUL_ENEMY_TAKKURI: MM2ShipItemData(200, IC.progression, 1),
    Items.SOUL_ENEMY_TEKTITE: MM2ShipItemData(201, IC.progression, 1),
    Items.SOUL_ENEMY_WALLMASTER: MM2ShipItemData(202, IC.progression, 1),
    Items.SOUL_ENEMY_WART: MM2ShipItemData(203, IC.progression, 1),
    Items.SOUL_ENEMY_WIZROBE: MM2ShipItemData(204, IC.progression, 1),
    Items.SOUL_ENEMY_WOLFOS: MM2ShipItemData(205, IC.progression, 1),
    Items.STONE_TOWER_BOSS_KEY: MM2ShipItemData(206, IC.progression, 1),
    Items.STONE_TOWER_COMPASS: MM2ShipItemData(207, IC.useful, 1),
    Items.STONE_TOWER_MAP: MM2ShipItemData(208, IC.useful, 1),
    Items.STONE_TOWER_SMALL_KEY: MM2ShipItemData(209, IC.progression, 1),
    Items.STONE_TOWER_STRAY_FAIRY: MM2ShipItemData(210, IC.useful, 1),
    Items.SWORD_GILDED: MM2ShipItemData(211, IC.progression, 1),
    Items.SWORD_KOKIRI: MM2ShipItemData(212, IC.progression, 1),
    Items.SWORD_RAZOR: MM2ShipItemData(213, IC.progression, 1),
    Items.TIME_DAY_1: MM2ShipItemData(214, IC.progression, 1),
    Items.TIME_DAY_2: MM2ShipItemData(215, IC.progression, 1),
    Items.TIME_DAY_3: MM2ShipItemData(216, IC.progression, 1),
    Items.TIME_NIGHT_1: MM2ShipItemData(217, IC.progression, 1),
    Items.TIME_NIGHT_2: MM2ShipItemData(218, IC.progression, 1),
    Items.TIME_NIGHT_3: MM2ShipItemData(219, IC.progression, 1),
    Items.TIME_PROGRESSIVE: MM2ShipItemData(220, IC.progression, 1),
    Items.TINGLE_MAP_CLOCK_TOWN: MM2ShipItemData(221, IC.useful, 1),
    Items.TINGLE_MAP_GREAT_BAY: MM2ShipItemData(222, IC.useful, 1),
    Items.TINGLE_MAP_ROMANI_RANCH: MM2ShipItemData(223, IC.useful, 1),
    Items.TINGLE_MAP_SNOWHEAD: MM2ShipItemData(224, IC.useful, 1),
    Items.TINGLE_MAP_STONE_TOWER: MM2ShipItemData(225, IC.useful, 1),
    Items.TINGLE_MAP_WOODFALL: MM2ShipItemData(226, IC.useful, 1),
    Items.TRAP: MM2ShipItemData(227, IC.trap, 1),
    # Items.TRIFORCE_PIECE_PREVIOUS: MM2ShipItemData(228, IC.progression, 1),
    Items.TRIFORCE_PIECE: MM2ShipItemData(229, IC.progression, 1),
    Items.WALLET_ADULT: MM2ShipItemData(230, IC.progression, 1),
    Items.WALLET_GIANT: MM2ShipItemData(231, IC.progression, 1),
    Items.WOODFALL_BOSS_KEY: MM2ShipItemData(232, IC.progression, 1),
    Items.WOODFALL_COMPASS: MM2ShipItemData(233, IC.useful, 1),
    Items.WOODFALL_MAP: MM2ShipItemData(234, IC.useful, 1),
    Items.WOODFALL_SMALL_KEY: MM2ShipItemData(235, IC.progression, 1),
    Items.WOODFALL_STRAY_FAIRY: MM2ShipItemData(236, IC.useful, 1),
    # Event items (not sent over network)
    Items.VICTORY: MM2ShipItemData(None, IC.progression, 0),
}

item_table = {name.value: data.item_id for name, data in item_data_table.items() if data.item_id is not None}

# No-logic phase: leave these empty or derive them later when you build the pool/options.
filler_items: list[Items] = []
no_rules_bottles: list[Items] = []
filler_bottles: list[Items] = []
all_bottles: list[Items] = []
progressive_items: dict[Items, tuple[Items, ...]] = {}

item_name_groups: dict[str, set[str]] = {}
for item, data in item_data_table.items():
    for group in data.item_groups:
        item_name_groups.setdefault(group, set()).add(item.value)
