# ============================================================================
# AUTO-GENERATED by worlds/mm_2ship/tools/genlogic — DO NOT EDIT BY HAND.
# Regenerate with:
#   python worlds/mm_2ship/tools/genlogic/generate.py /path/to/2ship2harkinian
# ============================================================================

"""Generated logic vocabulary: constants, helper predicates translated from
Logic.h macro bodies, the CanKillEnemy table, and item/flag grant maps
consumed by LogicRuntime."""

# ---- symbolic constants ----------------------------------------------
EQUIP_VALUE_SHIELD_MIRROR = 2
EQUIP_VALUE_SHIELD_NONE = 0
EQUIP_VALUE_SWORD_KOKIRI = 1
RO_ACCESS_TRIALS_20_MASKS = 0
RO_ACCESS_TRIALS_FORMS = 2
RO_ACCESS_TRIALS_OPEN = 3
RO_ACCESS_TRIALS_REMAINS = 1
RO_GENERIC_NO = 0
TIME_DAY1_AM_06_00 = 0
TIME_DAY1_AM_07_00 = 1
TIME_DAY1_AM_08_00 = 2
TIME_DAY1_AM_10_00 = 3
TIME_DAY1_PM_01_45 = 4
TIME_DAY1_PM_03_00 = 5
TIME_DAY1_PM_04_00 = 6
TIME_DAY2_AM_06_00 = 16
TIME_DAY2_AM_07_00 = 17
TIME_DAY2_AM_08_00 = 18
TIME_DAY2_AM_10_00 = 19
TIME_DAY2_PM_02_00 = 21
TIME_DAY2_PM_04_00 = 22
TIME_DAY3_AM_06_00 = 31
TIME_DAY3_AM_07_00 = 32
TIME_DAY3_AM_08_00 = 33
TIME_DAY3_AM_10_00 = 34
TIME_DAY3_AM_11_30 = 35
TIME_DAY3_PM_01_00 = 36
TIME_NIGHT1_AM_02_30 = 13
TIME_NIGHT1_AM_04_00 = 14
TIME_NIGHT1_AM_05_00 = 15
TIME_NIGHT1_AM_12_00 = 12
TIME_NIGHT1_PM_06_00 = 7
TIME_NIGHT1_PM_08_00 = 8
TIME_NIGHT1_PM_09_00 = 9
TIME_NIGHT1_PM_10_00 = 10
TIME_NIGHT1_PM_11_00 = 11
TIME_NIGHT2_AM_04_00 = 29
TIME_NIGHT2_AM_05_00 = 30
TIME_NIGHT2_AM_12_00 = 28
TIME_NIGHT2_PM_06_00 = 23
TIME_NIGHT2_PM_08_00 = 24
TIME_NIGHT2_PM_09_00 = 25
TIME_NIGHT2_PM_10_00 = 26
TIME_NIGHT2_PM_11_00 = 27
TIME_NIGHT3_AM_04_00 = 43
TIME_NIGHT3_AM_05_00 = 44
TIME_NIGHT3_AM_12_00 = 42
TIME_NIGHT3_PM_06_00 = 37
TIME_NIGHT3_PM_08_00 = 38
TIME_NIGHT3_PM_09_00 = 39
TIME_NIGHT3_PM_10_00 = 40
TIME_NIGHT3_PM_11_00 = 41

# (start_slice, end_slice) per half-day, from Logic.h HALF_DAY_TIME_RANGES
HALF_DAY_TIME_RANGES = [(0, 6), (7, 15), (16, 22), (23, 30), (31, 36), (37, 44)]

# ---- helper predicates (from Logic.h / region-local macros) ------------
def BREAK_BOULDER_BEFORE_OR_BEAT_ALIENS_DAY(s):
    return (s.time_between(TIME_DAY1_AM_06_00, TIME_NIGHT1_PM_06_00) and CAN_BE_GORON(s) and s.has_item('ITEM_POWDER_KEG')) or s.event('RE_COWS_FROM_ALIENS')

def BREAK_BOULDER_BEFORE_OR_BEAT_ALIENS_NIGHT(s):
    return (s.time_between(TIME_NIGHT1_PM_06_00, TIME_NIGHT1_AM_02_30) and CAN_BE_GORON(s) and s.has_item('ITEM_POWDER_KEG')) or s.event('RE_COWS_FROM_ALIENS')

def CAN_BE_DEITY(s):
    return s.is_form('DEITY') or s.has_item('ITEM_MASK_FIERCE_DEITY')

def CAN_BE_DEKU(s):
    return s.is_form('DEKU') or s.has_item('ITEM_MASK_DEKU')

def CAN_BE_GORON(s):
    return s.is_form('GORON') or s.has_item('ITEM_MASK_GORON')

def CAN_BE_ZORA(s):
    return s.is_form('ZORA') or s.has_item('ITEM_MASK_ZORA')

def CAN_GROW_BEAN_PLANT(s):
    return s.has_item('ITEM_MAGIC_BEANS') and (s.can_play_song('STORMS') or (s.has_bottle() and (s.can_access('SPRING_WATER') or s.can_access('HOT_SPRING_WATER'))))

def CAN_HOOK_SCARECROW(s):
    return s.has_item('ITEM_OCARINA_OF_TIME') and s.has_item('ITEM_HOOKSHOT') and s.can_play_notes('OCARINA_SONG_SCARECROW_SPAWN')

def CAN_LIGHT_TORCH_NEAR_ANOTHER(s):
    return s.has_item('ITEM_DEKU_STICK') or s.can_use_magic_arrow('FIRE')

def CAN_RIDE_EPONA(s):
    return s.can_play_song('EPONA')

def CAN_TRAVERSE_WAIST_DEEP_WATER(s):
    return s.ability('SWIM') or CAN_BE_DEKU(s) or CAN_BE_ZORA(s) or CAN_BE_GORON(s)

def CAN_USE_DAY2_RAIN_BEAN(s):
    return CAN_GROW_BEAN_PLANT(s) or (s.has_item('ITEM_MAGIC_BEANS') and CLOCK_DAY2(s))

def CAN_USE_EXPLOSIVE(s):
    return s.has_item('ITEM_BOMB') or s.has_item('ITEM_BOMBCHU') or (s.has_item('ITEM_MASK_BLAST') and (s.equip_value('EQUIP_TYPE_SHIELD') > EQUIP_VALUE_SHIELD_NONE))

def CAN_USE_HUMAN_SWORD(s):
    return s.equip_value('EQUIP_TYPE_SWORD') >= EQUIP_VALUE_SWORD_KOKIRI

def CAN_USE_PROJECTILE(s):
    return s.has_item('ITEM_BOW') or s.has_item('ITEM_HOOKSHOT') or (CAN_BE_DEKU(s) and s.has_magic()) or CAN_BE_ZORA(s)

def CAN_USE_SWORD(s):
    return CAN_USE_HUMAN_SWORD(s) or s.has_item('ITEM_SWORD_GREAT_FAIRY') or CAN_BE_DEITY(s)

def CLOCK_DAY1(s):
    return s.owns_half_day(0)

def CLOCK_DAY2(s):
    return s.owns_half_day(2)

def CLOCK_DAY3(s):
    return s.owns_half_day(4)

def CLOCK_NIGHT1(s):
    return s.owns_half_day(1)

def CLOCK_NIGHT2(s):
    return s.owns_half_day(3)

def CLOCK_NIGHT3(s):
    return s.owns_half_day(5)

def CanGetPastBigOcto(s):
    return s.event('RE_SOUTHERN_SWAMP_RIDE_BOAT') or CanGetPastBigOctoWithoutBoat(s)

def CanGetPastBigOctoWithoutBoat(s):
    return (s.event('RE_SOUTHERN_SWAMP_KILL_OCTOROK') and CAN_BE_DEKU(s)) or (s.event('RE_CLEARED_WOODFALL_TEMPLE') and CAN_TRAVERSE_WAIST_DEEP_WATER(s))

def ClockFilter(s):
    return (not SettingClocks(s)) or (IS_DAY1(s) or IS_NIGHT1(s) or IS_DAY2(s) or IS_NIGHT2(s) or IS_DAY3(s) or IS_NIGHT3(s))

def FINAL_DAY(s):
    return IS_DAY3(s) or IS_NIGHT3(s)

def FIRST_DAY(s):
    return IS_DAY1(s) or IS_NIGHT1(s)

def FOUND_ALL_FROGS(s):
    return s.weekeventreg('WEEKEVENTREG_33_01') and s.weekeventreg('WEEKEVENTREG_32_40') and s.weekeventreg('WEEKEVENTREG_32_80') and s.weekeventreg('WEEKEVENTREG_33_02')

def GBT_CAN_REVERSE_WATER_FLOW(s):
    return s.event('RE_GREAT_BAY_RED_SWITCH_1') and s.event('RE_GREAT_BAY_RED_SWITCH_2') and s.has_item('ITEM_HOOKSHOT')

def GBT_GREEN_SWITCH_FLOW(s):
    return s.event('RE_GREAT_BAY_GREEN_SWITCH_1') and s.event('RE_GREAT_BAY_GREEN_SWITCH_2') and s.event('RE_GREAT_BAY_GREEN_SWITCH_3')

def IS_DAY(s):
    return IS_DAY1(s) or IS_DAY2(s) or IS_DAY3(s)

def IS_DAY1(s):
    return s.raw_before(TIME_NIGHT1_PM_06_00) and CLOCK_DAY1(s)

def IS_DAY2(s):
    return s.raw_between(TIME_DAY2_AM_06_00, TIME_NIGHT2_PM_06_00) and CLOCK_DAY2(s)

def IS_DAY3(s):
    return s.raw_between(TIME_DAY3_AM_06_00, TIME_NIGHT3_PM_06_00) and CLOCK_DAY3(s)

def IS_NIGHT(s):
    return IS_NIGHT1(s) or IS_NIGHT2(s) or IS_NIGHT3(s)

def IS_NIGHT1(s):
    return s.raw_between(TIME_NIGHT1_PM_06_00, TIME_DAY2_AM_06_00) and CLOCK_NIGHT1(s)

def IS_NIGHT2(s):
    return s.raw_between(TIME_NIGHT2_PM_06_00, TIME_DAY3_AM_06_00) and CLOCK_NIGHT2(s)

def IS_NIGHT3(s):
    return s.raw_after(TIME_NIGHT3_PM_06_00) and CLOCK_NIGHT3(s)

def MIDNIGHT(s):
    return s.time_between(TIME_NIGHT1_AM_12_00, TIME_DAY2_AM_06_00) or s.time_between(TIME_NIGHT2_AM_12_00, TIME_DAY3_AM_06_00) or s.time_after(TIME_NIGHT3_AM_12_00)

def MeetsMoonRequirements(s):
    return (s.remains_count() >= s.opt('RO_ACCESS_MOON_REMAINS_COUNT')) and (s.moon_mask_count() >= s.opt('RO_ACCESS_MOON_MASKS_COUNT'))

def SECOND_DAY(s):
    return IS_DAY2(s) or IS_NIGHT2(s)

def SettingClocks(s):
    return s.opt('RO_CLOCK_SHUFFLE') != 0

# ---- CanKillEnemy ------------------------------------------------------
CAN_KILL_ENEMY = {
    'ACTOR_BOSS_01': lambda s: (CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_USE_EXPLOSIVE(s) or s.can_use_magic_arrow('FIRE') or s.can_use_magic_arrow('LIGHT')) and (s.rando_inf('RANDO_INF_OBTAINED_SOUL_OF_BOSS_ODOLWA') or (s.opt('RO_SHUFFLE_BOSS_SOULS') == RO_GENERIC_NO)),
    'ACTOR_BOSS_02': lambda s: (s.has_item('ITEM_BOW') or (s.has_item('ITEM_MASK_GIANT') and s.has_magic() and CAN_USE_HUMAN_SWORD(s))) and (s.rando_inf('RANDO_INF_OBTAINED_SOUL_OF_BOSS_TWINMOLD') or (s.opt('RO_SHUFFLE_BOSS_SOULS') == RO_GENERIC_NO)),
    'ACTOR_BOSS_03': lambda s: ((CAN_BE_DEITY(s) and s.has_magic()) or (CAN_BE_ZORA(s) and s.has_magic())) and (s.rando_inf('RANDO_INF_OBTAINED_SOUL_OF_BOSS_GYORG') or (s.opt('RO_SHUFFLE_BOSS_SOULS') == RO_GENERIC_NO)),
    'ACTOR_BOSS_04': lambda s: s.has_item('ITEM_BOW') or s.has_item('ITEM_HOOKSHOT') or CAN_BE_ZORA(s),
    'ACTOR_BOSS_05': lambda s: CAN_BE_ZORA(s) and s.ability('SWIM'),
    'ACTOR_BOSS_HAKUGIN': lambda s: s.can_use_magic_arrow('FIRE') and (s.rando_inf('RANDO_INF_OBTAINED_SOUL_OF_BOSS_GOHT') or (s.opt('RO_SHUFFLE_BOSS_SOULS') == RO_GENERIC_NO)),
    'ACTOR_EN_AM': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or CAN_USE_EXPLOSIVE(s),
    'ACTOR_EN_BAGUO': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_BAT': lambda s: CAN_USE_SWORD(s) or s.has_item('ITEM_HOOKSHOT') or s.has_item('ITEM_BOW') or CAN_USE_EXPLOSIVE(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s),
    'ACTOR_EN_BB': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_BBFALL': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_BEE': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_DEKU_STICK') or CAN_USE_PROJECTILE(s) or CAN_USE_EXPLOSIVE(s) or s.has_item('ITEM_DEKU_NUT'),
    'ACTOR_EN_BIGPAMET': lambda s: CAN_BE_DEKU(s) or CAN_USE_EXPLOSIVE(s) or CAN_BE_GORON(s),
    'ACTOR_EN_BIGPO': lambda s: s.has_item('ITEM_BOW'),
    'ACTOR_EN_BIGSLIME': lambda s: s.can_use_magic_arrow('ICE'),
    'ACTOR_EN_BSB': lambda s: s.has_item('ITEM_BOW') and (CAN_USE_SWORD(s) or s.has_item('ITEM_DEKU_STICK') or CAN_USE_EXPLOSIVE(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s)),
    'ACTOR_EN_CROW': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_DEATH': lambda s: CAN_USE_SWORD(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_HOOKSHOT') or CAN_BE_ZORA(s) or CAN_BE_GORON(s) or (CAN_BE_DEKU(s) and s.has_magic()),
    'ACTOR_EN_DEKUBABA': lambda s: CAN_USE_SWORD(s) or CAN_BE_DEKU(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.has_item('ITEM_BOW') or CAN_USE_EXPLOSIVE(s) or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_DEKUNUTS': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_DINOFOS': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or s.has_item('ITEM_BOW') or (CAN_BE_DEKU(s) and s.has_magic()),
    'ACTOR_EN_DODONGO': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()),
    'ACTOR_EN_DRAGON': lambda s: CAN_BE_ZORA(s) and s.has_magic(),
    'ACTOR_EN_EGOL': lambda s: CAN_USE_PROJECTILE(s),
    'ACTOR_EN_FAMOS': lambda s: s.can_use_magic_arrow('LIGHT'),
    'ACTOR_EN_FIREFLY': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_FLOORMAS': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_FZ': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.can_use_magic_arrow('FIRE') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_GRASSHOPPER': lambda s: (CAN_BE_DEKU(s) and s.has_magic()) or CAN_USE_EXPLOSIVE(s) or s.has_item('ITEM_DEKU_NUT') or CAN_USE_SWORD(s) or CAN_BE_ZORA(s),
    'ACTOR_EN_IK': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s),
    'ACTOR_EN_INVADEPOH': lambda s: s.has_item('ITEM_BOW'),
    'ACTOR_EN_JSO': lambda s: s.has_item('ITEM_MASK_GARO') and (s.has_item('ITEM_BOW') or CAN_BE_GORON(s) or CAN_USE_SWORD(s)),
    'ACTOR_EN_JSO2': lambda s: s.has_item('ITEM_BOW') or CAN_BE_GORON(s) or CAN_USE_SWORD(s),
    'ACTOR_EN_KAIZOKU': lambda s: CAN_USE_SWORD(s) or CAN_BE_ZORA(s),
    'ACTOR_EN_KAME': lambda s: CAN_USE_EXPLOSIVE(s) or CAN_BE_GORON(s),
    'ACTOR_EN_KAREBABA': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s),
    'ACTOR_EN_KNIGHT': lambda s: s.can_use_magic_arrow('FIRE') and (s.equip_value('EQUIP_TYPE_SHIELD') >= EQUIP_VALUE_SHIELD_MIRROR) and (CAN_USE_SWORD(s) or CAN_BE_DEKU(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s)),
    'ACTOR_EN_MKK': lambda s: (CAN_BE_DEKU(s) and s.has_magic()) or CAN_USE_EXPLOSIVE(s) or s.has_item('ITEM_DEKU_NUT') or CAN_USE_SWORD(s) or CAN_BE_ZORA(s) or CAN_BE_GORON(s),
    'ACTOR_EN_NEO_REEBA': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_OKUTA': lambda s: CAN_USE_PROJECTILE(s),
    'ACTOR_EN_PAMETFROG': lambda s: s.has_item('ITEM_BOW') and CanKillEnemy(s, 'ACTOR_EN_BIGPAMET'),
    'ACTOR_EN_PEEHAT': lambda s: (CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_DEKU_STICK')) and IS_DAY(s),
    'ACTOR_EN_PO_SISTERS': lambda s: CAN_USE_PROJECTILE(s) or s.has_item('ITEM_BOMB') or s.has_item('ITEM_BOMBCHU'),
    'ACTOR_EN_PP': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_PR': lambda s: CAN_BE_ZORA(s) and s.has_magic() and s.ability('SWIM'),
    'ACTOR_EN_PR2': lambda s: CAN_BE_ZORA(s) and s.has_magic() and s.ability('SWIM'),
    'ACTOR_EN_RAT': lambda s: True,
    'ACTOR_EN_RD': lambda s: CAN_USE_SWORD(s) or CAN_BE_DEKU(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_RR': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_SB': lambda s: CAN_BE_ZORA(s) and s.has_magic() and s.ability('SWIM'),
    'ACTOR_EN_SKB': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_SLIME': lambda s: CAN_USE_SWORD(s) or CAN_BE_ZORA(s) or CAN_BE_DEKU(s) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_SNOWMAN': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK') or s.has_item('ITEM_HOOKSHOT'),
    'ACTOR_EN_ST': lambda s: CAN_USE_SWORD(s) or CAN_USE_PROJECTILE(s) or CAN_BE_GORON(s) or CAN_USE_EXPLOSIVE(s),
    'ACTOR_EN_SW': lambda s: CAN_USE_PROJECTILE(s) or CAN_BE_DEKU(s) or CAN_BE_GORON(s) or CAN_USE_SWORD(s) or CAN_USE_EXPLOSIVE(s),
    'ACTOR_EN_THIEFBIRD': lambda s: CAN_USE_PROJECTILE(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or CAN_USE_EXPLOSIVE(s) or CAN_USE_SWORD(s),
    'ACTOR_EN_TITE': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW'),
    'ACTOR_EN_TUBO_TRAP': lambda s: True,
    'ACTOR_EN_VM': lambda s: CAN_USE_EXPLOSIVE(s),
    'ACTOR_EN_WALLMAS': lambda s: CAN_USE_SWORD(s) or CAN_BE_GORON(s) or CAN_BE_ZORA(s) or (CAN_BE_DEKU(s) and s.has_magic()) or s.has_item('ITEM_BOW') or s.has_item('ITEM_DEKU_STICK'),
    'ACTOR_EN_WDHAND': lambda s: CAN_BE_ZORA(s) and s.has_magic(),
    'ACTOR_EN_WF': lambda s: CAN_USE_SWORD(s) or (CAN_BE_DEKU(s) and s.has_magic()) or CAN_BE_GORON(s) or CAN_BE_ZORA(s),
    'ACTOR_EN_WIZ': lambda s: s.has_item('ITEM_BOW') or s.has_item('ITEM_HOOKSHOT') or CAN_USE_SWORD(s) or CAN_BE_GORON(s),
    'ACTOR_OBJ_SNOWBALL': lambda s: CAN_USE_EXPLOSIVE(s) or CAN_BE_GORON(s) or s.can_use_magic_arrow('FIRE'),
}

def CanKillEnemy(s, actor):
    if s.opt('RO_SHUFFLE_ENEMY_SOULS') and not s.have_enemy_soul(actor):
        return False
    fn = CAN_KILL_ENEMY.get(actor)
    if fn is None:
        raise KeyError(f'CanKillEnemy: no logic for {actor}')
    return fn(s)

# ---- RANDO_INF flag -> granting item names ----
RANDO_INF_TO_ITEMS = {
    'RANDO_INF_OBTAINED_CLOCK_DAY_1': ['Time (Day 1)'],
    'RANDO_INF_OBTAINED_CLOCK_DAY_2': ['Time (Day 3)'],
    'RANDO_INF_OBTAINED_CLOCK_DAY_3': ['Time (Night 2)'],
    'RANDO_INF_OBTAINED_CLOCK_NIGHT_1': ['Time (Day 2)'],
    'RANDO_INF_OBTAINED_CLOCK_NIGHT_2': ['Time (Night 1)'],
    'RANDO_INF_OBTAINED_CLOCK_NIGHT_3': ['Time (Night 3)'],
    'RANDO_INF_OBTAINED_DEED_LAND': ['Land Title Deed'],
    'RANDO_INF_OBTAINED_DEED_MOUNTAIN': ['Mountain Title Deed'],
    'RANDO_INF_OBTAINED_DEED_OCEAN': ['Ocean Title Deed'],
    'RANDO_INF_OBTAINED_DEED_SWAMP': ['Swamp Title Deed'],
    'RANDO_INF_OBTAINED_LETTER_TO_KAFEI': ['Letter to Kafei'],
    'RANDO_INF_OBTAINED_LETTER_TO_MAMA': ['Letter to Mama'],
    'RANDO_INF_OBTAINED_MOONS_TEAR': ["Moon's Tear"],
    'RANDO_INF_OBTAINED_OCARINA_BUTTON_A': ['A Button'],
    'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN': ['C Down Button'],
    'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT': ['C Left Button'],
    'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT': ['C Right Button'],
    'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP': ['C Up Button'],
    'RANDO_INF_OBTAINED_PENDANT_OF_MEMORIES': ['Pendant of Memories'],
    'RANDO_INF_OBTAINED_ROOM_KEY': ['Room Key'],
    'RANDO_INF_OBTAINED_SONG_DOUBLE_TIME': ['Song of Double Time'],
    'RANDO_INF_OBTAINED_SONG_INVERTED_TIME': ['Inverted Song of Time'],
    'RANDO_INF_OBTAINED_SOUL_OF_BOSS_GOHT': ['Soul of Goht'],
    'RANDO_INF_OBTAINED_SOUL_OF_BOSS_GYORG': ['Soul of Gyorg'],
    'RANDO_INF_OBTAINED_SOUL_OF_BOSS_MAJORA': ['Soul of Majora'],
    'RANDO_INF_OBTAINED_SOUL_OF_BOSS_ODOLWA': ['Soul of Odolwa'],
    'RANDO_INF_OBTAINED_SOUL_OF_BOSS_TWINMOLD': ['Soul of Twinmold'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_ALIENS': ['Soul of Aliens'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_ARMOS': ['Soul of Armos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BAD_BATS': ['Soul of Bad Bats'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BEAMOS': ['Soul of Beamos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BOES': ['Soul of Boes'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BUBBLES': ['Soul of Bubbles'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_CAPTAIN_KEETA': ['Soul of Captain Keeta'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_CHUCHUS': ['Soul of Chuchus'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEATH_ARMOS': ['Soul of Death Armos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEEP_PYTHONS': ['Soul of Deep Pythons'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEKU_BABAS': ['Soul of Deku Babas'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEXIHANDS': ['Soul of Dexihands'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DINOLFOS': ['Soul of Dinolfos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DODONGOS': ['Soul of Dodongos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DRAGONFLIES': ['Soul of Dragonflies'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_EENOS': ['Soul of Eenos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_EYEGORES': ['Soul of Eyegores'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_FREEZARDS': ['Soul of Freezards'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GAROS': ['Soul of Garos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GEKKOS': ['Soul of Gekkos'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GIANT_BEES': ['Soul of Giant Bees'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GOMESS': ['Soul of Gomess'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GUAYS': ['Soul of Guays'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_HIPLOOPS': ['Soul of Hiploops'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_IGOS_DU_IKANA': ['Soul of Igos du Ikana'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_IRON_KNUCKLES': ['Soul of Iron Knuckles'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_KEESE': ['Soul of Keese'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_LEEVERS': ['Soul of Leevers'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_LIKE_LIKES': ['Soul of Like Likes'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_MAD_SCRUBS': ['Soul of Mad Scrubs'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_NEJIRONS': ['Soul of Nejirons'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_OCTOROKS': ['Soul of Octoroks'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_PEAHATS': ['Soul of Peahats'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_PIRATES': ['Soul of Pirates'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_POES': ['Soul of Poes'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_REDEADS': ['Soul of Redeads'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SHELLBLADES': ['Soul of Shellblades'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SKULLFISH': ['Soul of Skullfish'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SKULLTULAS': ['Soul of Skulltulas'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SNAPPERS': ['Soul of Snappers'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_STALCHILDREN': ['Soul of Stalchildren'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_TAKKURI': ['Soul of Takkuri'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_TEKTITES': ['Soul of Tektites'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WALLMASTERS': ['Soul of Wallmasters'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WARTS': ['Soul of Warts'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WIZROBES': ['Soul of Wizrobes'],
    'RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WOLFOS': ['Soul of Wolfos'],
    'RANDO_INF_OBTAINED_SWIM': ['Ability to Swim'],
}

# ---- WEEKEVENTREG -> granting item names ----
WEEKEVENTREG_TO_ITEMS = {
    'WEEKEVENTREG_08_80': ['Clock Town Stray Fairy'],
    'WEEKEVENTREG_12_80': ['Magic Upgrade', 'Power of Magic'],
    'WEEKEVENTREG_32_40': ['Cyan Frog'],
    'WEEKEVENTREG_32_80': ['Pink Frog'],
    'WEEKEVENTREG_33_01': ['Blue Frog'],
    'WEEKEVENTREG_33_02': ['White Frog'],
    'WEEKEVENTREG_HAS_POWDERKEG_PRIVILEGES': ['Powder Keg'],
    'WEEKEVENTREG_RECEIVED_GREAT_SPIN_ATTACK': ['Great Spin Attack'],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_CLOCK_TOWN': ["Tingle's Clock Town Map"],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_GREAT_BAY': ["Tingle's Great Bay Map"],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_ROMANI_RANCH': ["Tingle's Romani Ranch Map"],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_SNOWHEAD': ["Tingle's Snowhead Map"],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_STONE_TOWER': ["Tingle's Stone Tower Map"],
    'WEEKEVENTREG_TINGLE_MAP_BOUGHT_WOODFALL': ["Tingle's Woodfall Map"],
}

# ---- skulltula token scene -> granting item names ----
TOKEN_SCENE_TO_ITEMS = {
    'SCENE_KINDAN2': ['Ocean Gold Skulltula Token'],
    'SCENE_KINSTA1': ['Swamp Gold Skulltula Token'],
}

# ---- owl warp -> granting item names ----
OWL_WARP_TO_ITEMS = {
    'OWL_WARP_CLOCK_TOWN': ['Clock Town Owl Statue'],
    'OWL_WARP_GREAT_BAY_COAST': ['Great Bay Coast Owl Statue'],
    'OWL_WARP_IKANA_CANYON': ['Ikana Canyon Owl Statue'],
    'OWL_WARP_MILK_ROAD': ['Milk Road Owl Statue'],
    'OWL_WARP_MOUNTAIN_VILLAGE': ['Mountain Village Owl Statue'],
    'OWL_WARP_SNOWHEAD': ['Snowhead Owl Statue'],
    'OWL_WARP_SOUTHERN_SWAMP': ['Southern Swamp Owl Statue'],
    'OWL_WARP_STONE_TOWER': ['Stone Tower Owl Statue'],
    'OWL_WARP_WOODFALL': ['Woodfall Owl Statue'],
    'OWL_WARP_ZORA_CAPE': ['Zora Cape Owl Statue'],
}

# ---- quest item -> granting item names (Item_Give parallel ranges) ----
QUEST_TO_ITEMS = {
    'QUEST_REMAINS_GOHT': ["Goht's Remains"],
    'QUEST_REMAINS_GYORG': ["Gyorg's Remains"],
    'QUEST_REMAINS_ODOLWA': ["Odolwa's Remains"],
    'QUEST_REMAINS_TWINMOLD': ["Twinmold's Remains"],
    'QUEST_SONG_BOSSA_NOVA': ['New Wave Bossa Nova'],
    'QUEST_SONG_ELEGY': ['Elegy of Emptiness'],
    'QUEST_SONG_EPONA': ["Epona's Song"],
    'QUEST_SONG_HEALING': ['Song of Healing'],
    'QUEST_SONG_LULLABY': ['Goron Lullaby'],
    'QUEST_SONG_LULLABY_INTRO': ['Goron Lullaby Intro'],
    'QUEST_SONG_OATH': ['Oath to Order'],
    'QUEST_SONG_SARIA': ["Saria's Song"],
    'QUEST_SONG_SOARING': ['Song of Soaring'],
    'QUEST_SONG_SONATA': ['Sonata of Awakening'],
    'QUEST_SONG_STORMS': ['Song of Storms'],
    'QUEST_SONG_SUN': ["Sun's Song"],
    'QUEST_SONG_TIME': ['Song of Time'],
}

# ---- vanilla inventory item -> granting item names ----
ITEM_TO_ITEMS = {
    'ITEM_ARROWS_10': ['10 Arrows'],
    'ITEM_ARROWS_30': ['30 Arrows'],
    'ITEM_ARROWS_50': ['50 Arrows'],
    'ITEM_ARROW_FIRE': ['Fire Arrows'],
    'ITEM_ARROW_ICE': ['Ice Arrows'],
    'ITEM_ARROW_LIGHT': ['Light Arrows'],
    'ITEM_BOMBCHU': ['10 Bombchus', '5 Bombchus', 'Bombchu'],
    'ITEM_BOMBERS_NOTEBOOK': ["Bomber's Notebook"],
    'ITEM_BOMBS_10': ['10 Bombs'],
    'ITEM_BOMBS_5': ['5 Bombs'],
    'ITEM_BOMB_BAG_20': ['Bomb Bag', 'Progressive Bomb Bag'],
    'ITEM_BOMB_BAG_30': ['Big Bomb Bag'],
    'ITEM_BOMB_BAG_40': ['Biggest Bomb Bag'],
    'ITEM_BOTTLE': ['Empty Bottle'],
    'ITEM_BOW': ['Bow', 'Progressive Bow'],
    'ITEM_CHATEAU': ['Bottle of Chateau Romani'],
    'ITEM_CHATEAU_2': ['Chateau Romani Refill'],
    'ITEM_COMPASS': ['Great Bay Compass', 'Snowhead Compass', 'Stone Tower Compass', 'Woodfall Compass'],
    'ITEM_DEED_LAND': ['Land Title Deed'],
    'ITEM_DEED_MOUNTAIN': ['Mountain Title Deed'],
    'ITEM_DEED_OCEAN': ['Ocean Title Deed'],
    'ITEM_DEED_SWAMP': ['Swamp Title Deed'],
    'ITEM_DEKU_NUT': ['10 Deku Nuts', '5 Deku Nuts', 'Deku Nut'],
    'ITEM_DEKU_STICK': ['5 Deku Sticks', 'Deku Stick'],
    'ITEM_DUNGEON_MAP': ['Great Bay Map', 'Snowhead Map', 'Stone Tower Map', 'Woodfall Map'],
    'ITEM_FAIRY': ['Fairy'],
    'ITEM_GOLD_DUST': ['Bottle With Gold Dust'],
    'ITEM_GOLD_DUST_2': ['Gold Dust Refill'],
    'ITEM_HEART_CONTAINER': ['Heart Container'],
    'ITEM_HEART_PIECE': ['Heart Piece'],
    'ITEM_HOOKSHOT': ['Hookshot'],
    'ITEM_KEY_BOSS': ['Great Bay Boss Key', 'Snowhead Boss Key', 'Stone Tower Boss Key', 'Woodfall Boss Key'],
    'ITEM_KEY_SMALL': ['Great Bay Small Key', 'Snowhead Small Key', 'Stone Tower Small Key', 'Woodfall Small Key'],
    'ITEM_LENS_OF_TRUTH': ['Lens of Truth'],
    'ITEM_LETTER_MAMA': ['Letter to Mama'],
    'ITEM_LETTER_TO_KAFEI': ['Letter to Kafei'],
    'ITEM_MAGIC_BEANS': ['Magic Bean'],
    'ITEM_MAGIC_JAR_BIG': ['Large Magic Refill'],
    'ITEM_MAGIC_JAR_SMALL': ['Small Magic Refill'],
    'ITEM_MASK_ALL_NIGHT': ['All-Night Mask'],
    'ITEM_MASK_BLAST': ['Blast Mask'],
    'ITEM_MASK_BREMEN': ['Bremen Mask'],
    'ITEM_MASK_BUNNY': ['Bunny Hood'],
    'ITEM_MASK_CAPTAIN': ["Captain's Hat"],
    'ITEM_MASK_CIRCUS_LEADER': ["Circus Leader's Mask"],
    'ITEM_MASK_COUPLE': ['Couples Mask'],
    'ITEM_MASK_DEKU': ['Deku Mask'],
    'ITEM_MASK_DON_GERO': ['Don Gero Mask'],
    'ITEM_MASK_FIERCE_DEITY': ['Fierce Deity Mask'],
    'ITEM_MASK_GARO': ["Garo's Mask"],
    'ITEM_MASK_GIANT': ["Giant's Mask"],
    'ITEM_MASK_GIBDO': ['Gibdo Mask'],
    'ITEM_MASK_GORON': ['Goron Mask'],
    'ITEM_MASK_GREAT_FAIRY': ['Great Fairy Mask'],
    'ITEM_MASK_KAFEIS_MASK': ["Kafei's Mask"],
    'ITEM_MASK_KAMARO': ["Kamaro's Mask"],
    'ITEM_MASK_KEATON': ['Keaton Mask'],
    'ITEM_MASK_POSTMAN': ["Postman's Hat"],
    'ITEM_MASK_ROMANI': ["Romani's Mask"],
    'ITEM_MASK_SCENTS': ['Mask of Scents'],
    'ITEM_MASK_STONE': ['Stone Mask'],
    'ITEM_MASK_TRUTH': ['Mask of Truth'],
    'ITEM_MASK_ZORA': ['Zora Mask'],
    'ITEM_MILK': ['Milk Refill'],
    'ITEM_MILK_BOTTLE': ['Bottle of Milk'],
    'ITEM_MOONS_TEAR': ["Moon's Tear"],
    'ITEM_MUSHROOM': ['Magic Mushroom'],
    'ITEM_OCARINA_OF_TIME': ['Ocarina of Time'],
    'ITEM_PENDANT_OF_MEMORIES': ['Pendant of Memories'],
    'ITEM_PICTOGRAPH_BOX': ['Pictograph Box'],
    'ITEM_POTION_BLUE': ['Blue Potion Refill'],
    'ITEM_POTION_GREEN': ['Green Potion Refill'],
    'ITEM_POTION_RED': ['Bottle with Red Potion', 'Red Potion Refill'],
    'ITEM_POWDER_KEG': ['Powder Keg'],
    'ITEM_QUIVER_40': ['Large Quiver'],
    'ITEM_QUIVER_50': ['Largest Quiver'],
    'ITEM_RECOVERY_HEART': ['Recovery Heart'],
    'ITEM_REMAINS_GOHT': ["Goht's Remains"],
    'ITEM_REMAINS_GYORG': ["Gyorg's Remains"],
    'ITEM_REMAINS_ODOLWA': ["Odolwa's Remains"],
    'ITEM_REMAINS_TWINMOLD': ["Twinmold's Remains"],
    'ITEM_ROOM_KEY': ['Room Key'],
    'ITEM_RUPEE_BLUE': ['Blue Rupee'],
    'ITEM_RUPEE_GREEN': ['Green Rupee'],
    'ITEM_RUPEE_HUGE': ['Huge Rupee'],
    'ITEM_RUPEE_PURPLE': ['Purple Rupee'],
    'ITEM_RUPEE_RED': ['Red Rupee'],
    'ITEM_RUPEE_SILVER': ['Silver Rupee'],
    'ITEM_SHIELD_HERO': ["Hero's Shield"],
    'ITEM_SHIELD_MIRROR': ['Mirror Shield'],
    'ITEM_SKULL_TOKEN': ['Ocean Gold Skulltula Token', 'Swamp Gold Skulltula Token'],
    'ITEM_SONG_ELEGY': ['Elegy of Emptiness'],
    'ITEM_SONG_EPONA': ["Epona's Song"],
    'ITEM_SONG_HEALING': ['Song of Healing'],
    'ITEM_SONG_LULLABY': ['Goron Lullaby'],
    'ITEM_SONG_LULLABY_INTRO': ['Goron Lullaby Intro'],
    'ITEM_SONG_NOVA': ['New Wave Bossa Nova'],
    'ITEM_SONG_OATH': ['Oath to Order'],
    'ITEM_SONG_SARIA': ["Saria's Song"],
    'ITEM_SONG_SOARING': ['Song of Soaring'],
    'ITEM_SONG_SONATA': ['Sonata of Awakening'],
    'ITEM_SONG_STORMS': ['Song of Storms'],
    'ITEM_SONG_SUN': ["Sun's Song"],
    'ITEM_SONG_TIME': ['Song of Time'],
    'ITEM_STRAY_FAIRIES': ['Clock Town Stray Fairy', 'Great Bay Stray Fairy', 'Snowhead Stray Fairy', 'Stone Tower Stray Fairy', 'Woodfall Stray Fairy'],
    'ITEM_SWORD_GILDED': ['Gilded Sword'],
    'ITEM_SWORD_GREAT_FAIRY': ["Great Fairy's Sword"],
    'ITEM_SWORD_KOKIRI': ['Kokiri Sword'],
    'ITEM_SWORD_RAZOR': ['Razor Sword'],
    'ITEM_TINGLE_MAP': ["Tingle's Clock Town Map", "Tingle's Great Bay Map", "Tingle's Romani Ranch Map", "Tingle's Snowhead Map", "Tingle's Stone Tower Map", "Tingle's Woodfall Map"],
    'ITEM_WALLET_ADULT': ["Adult's Wallet"],
    'ITEM_WALLET_GIANT': ["Giant's Wallet"],
}

# ---- enemy souls -------------------------------------------------------
ACTOR_TO_SOUL_ITEM = {
    'ACTOR_BOSS_04': 'Soul of Warts',
    'ACTOR_BOSS_05': 'Soul of Deku Babas',
    'ACTOR_EN_AM': 'Soul of Armos',
    'ACTOR_EN_BAGUO': 'Soul of Nejirons',
    'ACTOR_EN_BAT': 'Soul of Bad Bats',
    'ACTOR_EN_BB': 'Soul of Bubbles',
    'ACTOR_EN_BBFALL': 'Soul of Bubbles',
    'ACTOR_EN_BEE': 'Soul of Giant Bees',
    'ACTOR_EN_BIGPAMET': 'Soul of Snappers',
    'ACTOR_EN_BIGPO': 'Soul of Poes',
    'ACTOR_EN_BIGSLIME': 'Soul of Gekkos',
    'ACTOR_EN_BSB': 'Soul of Captain Keeta',
    'ACTOR_EN_CROW': 'Soul of Guays',
    'ACTOR_EN_DEATH': 'Soul of Gomess',
    'ACTOR_EN_DEKUBABA': 'Soul of Deku Babas',
    'ACTOR_EN_DEKUNUTS': 'Soul of Mad Scrubs',
    'ACTOR_EN_DINOFOS': 'Soul of Dinolfos',
    'ACTOR_EN_DODONGO': 'Soul of Dodongos',
    'ACTOR_EN_DRAGON': 'Soul of Deep Pythons',
    'ACTOR_EN_EGOL': 'Soul of Eyegores',
    'ACTOR_EN_FAMOS': 'Soul of Death Armos',
    'ACTOR_EN_FIREFLY': 'Soul of Keese',
    'ACTOR_EN_FLOORMAS': 'Soul of Wallmasters',
    'ACTOR_EN_FZ': 'Soul of Freezards',
    'ACTOR_EN_GRASSHOPPER': 'Soul of Dragonflies',
    'ACTOR_EN_HINT_SKB': 'Soul of Stalchildren',
    'ACTOR_EN_IK': 'Soul of Iron Knuckles',
    'ACTOR_EN_INVADEPOH': 'Soul of Aliens',
    'ACTOR_EN_JSO': 'Soul of Garos',
    'ACTOR_EN_JSO2': 'Soul of Garos',
    'ACTOR_EN_KAIZOKU': 'Soul of Pirates',
    'ACTOR_EN_KAME': 'Soul of Snappers',
    'ACTOR_EN_KAREBABA': 'Soul of Deku Babas',
    'ACTOR_EN_KNIGHT': 'Soul of Igos du Ikana',
    'ACTOR_EN_MINIDEATH': 'Soul of Gomess',
    'ACTOR_EN_MKK': 'Soul of Boes',
    'ACTOR_EN_NEO_REEBA': 'Soul of Leevers',
    'ACTOR_EN_OKUTA': 'Soul of Octoroks',
    'ACTOR_EN_PAMETFROG': 'Soul of Gekkos',
    'ACTOR_EN_PEEHAT': 'Soul of Peahats',
    'ACTOR_EN_POH': 'Soul of Poes',
    'ACTOR_EN_PO_SISTERS': 'Soul of Poes',
    'ACTOR_EN_PP': 'Soul of Hiploops',
    'ACTOR_EN_PR': 'Soul of Skullfish',
    'ACTOR_EN_PR2': 'Soul of Skullfish',
    'ACTOR_EN_PRZ': 'Soul of Skullfish',
    'ACTOR_EN_RAIL_SKB': 'Soul of Stalchildren',
    'ACTOR_EN_RD': 'Soul of Redeads',
    'ACTOR_EN_RR': 'Soul of Like Likes',
    'ACTOR_EN_RUPPECROW': 'Soul of Guays',
    'ACTOR_EN_SB': 'Soul of Shellblades',
    'ACTOR_EN_SKB': 'Soul of Stalchildren',
    'ACTOR_EN_SLIME': 'Soul of Chuchus',
    'ACTOR_EN_SNOWMAN': 'Soul of Eenos',
    'ACTOR_EN_ST': 'Soul of Skulltulas',
    'ACTOR_EN_SW': 'Soul of Skulltulas',
    'ACTOR_EN_TANRON2': 'Soul of Warts',
    'ACTOR_EN_THIEFBIRD': 'Soul of Takkuri',
    'ACTOR_EN_TITE': 'Soul of Tektites',
    'ACTOR_EN_VM': 'Soul of Beamos',
    'ACTOR_EN_WALLMAS': 'Soul of Wallmasters',
    'ACTOR_EN_WDHAND': 'Soul of Dexihands',
    'ACTOR_EN_WF': 'Soul of Wolfos',
    'ACTOR_EN_WIZ': 'Soul of Wizrobes',
}

# ---- song note requirements (from Logic.h canPlaySong) ------------------
SONG_NOTE_REQS = {
    'OCARINA_SONG_DOUBLE_TIME': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_ELEGY': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_EPONAS': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT']),
    'OCARINA_SONG_EVAN_PART1': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_EVAN_PART2': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_GORON_LULLABY': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT']),
    'OCARINA_SONG_GORON_LULLABY_INTRO': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT']),
    'OCARINA_SONG_HEALING': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_INVERTED_TIME': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_NEW_WAVE': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_OATH': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP']),
    'OCARINA_SONG_SARIAS': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_SCARECROW_SPAWN': ('count', 2),
    'OCARINA_SONG_SOARING': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP']),
    'OCARINA_SONG_SONATA': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT']),
    'OCARINA_SONG_STORMS': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP']),
    'OCARINA_SONG_SUNS': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP']),
    'OCARINA_SONG_TIME': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_WIND_FISH_DEKU': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT']),
    'OCARINA_SONG_WIND_FISH_GORON': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN']),
    'OCARINA_SONG_WIND_FISH_HUMAN': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT']),
    'OCARINA_SONG_WIND_FISH_ZORA': ('all', ['RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_A', 'RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP']),
}

# QUEST_SONG_* -> OCARINA_SONG_* (offset mapping from the C++ enums)
QUEST_TO_OCARINA = {
    'QUEST_SONG_BOSSA_NOVA': 'OCARINA_SONG_NEW_WAVE',
    'QUEST_SONG_ELEGY': 'OCARINA_SONG_ELEGY',
    'QUEST_SONG_EPONA': 'OCARINA_SONG_EPONAS',
    'QUEST_SONG_HEALING': 'OCARINA_SONG_HEALING',
    'QUEST_SONG_LULLABY': 'OCARINA_SONG_GORON_LULLABY',
    'QUEST_SONG_LULLABY_INTRO': 'OCARINA_SONG_WIND_FISH_DEKU',
    'QUEST_SONG_OATH': 'OCARINA_SONG_OATH',
    'QUEST_SONG_SARIA': 'OCARINA_SONG_SARIAS',
    'QUEST_SONG_SOARING': 'OCARINA_SONG_SOARING',
    'QUEST_SONG_SONATA': 'OCARINA_SONG_SONATA',
    'QUEST_SONG_STORMS': 'OCARINA_SONG_STORMS',
    'QUEST_SONG_SUN': 'OCARINA_SONG_SUNS',
    'QUEST_SONG_TIME': 'OCARINA_SONG_TIME',
}

# ---- dungeons ------------------------------------------------------------
DUNGEON_ITEMS = {
    'GREAT_BAY_TEMPLE': {'small_key': 'Great Bay Small Key', 'boss_key': 'Great Bay Boss Key', 'stray_fairy': 'Great Bay Stray Fairy'},
    'SNOWHEAD_TEMPLE': {'small_key': 'Snowhead Small Key', 'boss_key': 'Snowhead Boss Key', 'stray_fairy': 'Snowhead Stray Fairy'},
    'STONE_TOWER_TEMPLE': {'small_key': 'Stone Tower Small Key', 'boss_key': 'Stone Tower Boss Key', 'stray_fairy': 'Stone Tower Stray Fairy'},
    'WOODFALL_TEMPLE': {'small_key': 'Woodfall Small Key', 'boss_key': 'Woodfall Boss Key', 'stray_fairy': 'Woodfall Stray Fairy'},
}

# Masks counted by MoonMaskCount() (ITEM_MASK_TRUTH..ITEM_MASK_GIANT)
MOON_MASK_ITEMS = ['All-Night Mask', 'Blast Mask', 'Bremen Mask', 'Bunny Hood', "Captain's Hat", "Circus Leader's Mask", 'Couples Mask', 'Don Gero Mask', "Garo's Mask", "Giant's Mask", 'Gibdo Mask', 'Great Fairy Mask', "Kafei's Mask", "Kamaro's Mask", 'Keaton Mask', 'Mask of Scents', 'Mask of Truth', "Postman's Hat", "Romani's Mask", 'Stone Mask']

REMAINS_ITEMS = ["Goht's Remains", "Gyorg's Remains", "Odolwa's Remains", "Twinmold's Remains"]

BOTTLE_ITEMS = ['Bottle of Chateau Romani', 'Empty Bottle', 'Bottle With Gold Dust', 'Bottle of Milk', 'Bottle with Red Potion']
