"""
Generated-file writers.

All output is deterministic (stable ordering) so regeneration diffs are
reviewable. Every file carries a DO-NOT-EDIT banner naming this pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

BANNER = (
    "# ============================================================================\n"
    "# AUTO-GENERATED by worlds/mm_2ship/tools/genlogic — DO NOT EDIT BY HAND.\n"
    "# Regenerate with:\n"
    "#   python worlds/mm_2ship/tools/genlogic/generate.py /path/to/2ship2harkinian\n"
    "# ============================================================================\n"
)


# When two RI entries share a display name, the AP item enum keeps only one.
# The winner must match what the game client resolves that name to — see the
# "Piece of the Triforce" special case in Archipelago.cpp's
# GetRandoItemIdFromNetworkItem.
CANONICAL_NAME_WINNERS = {
    "Piece of the Triforce": "RI_TRIFORCE_PIECE",
}


@dataclass
class EmitContext:
    apworld_root: Path
    rc_order: list[str]
    ri_order: list[str]
    rr_order: list[str]
    re_order: list[str]
    checks: dict[str, dict]
    items: dict[str, dict]
    options: dict[str, dict]
    translated_regions: dict[str, dict]
    helpers: dict[str, str]
    constants: dict[str, int]
    can_kill: dict[str, str]
    soul_map: dict[str, str]                 # ACTOR_* -> RI_*
    rando_inf_grants: dict[str, list[str]]   # RANDO_INF_* -> [RI_*]
    weekevent_grants: dict[str, list[str]]   # WEEKEVENTREG_* -> [RI_*]
    scene_to_dungeon: dict[str, str]         # SCENE_* -> DUNGEON_SCENE_INDEX_*
    item_to_dungeon: dict[str, str]          # RI_* -> DUNGEON_SCENE_INDEX_*
    song_note_reqs: dict[str, tuple[str, object]]
    progression_items: set[str]              # RI_*
    item_ids: dict[str, int]                 # enum key (no RI_) -> AP id
    display_name: Callable[[str], str]
    enums: dict[str, list[tuple[str, int]]]
    token_scene_grants: dict[str, list[str]] | None = None  # SCENE_* -> [RI_*]
    owl_grants: dict[str, list[str]] | None = None           # OWL_WARP_* -> [RI_*]
    item_grants: dict[str, list[str]] | None = None          # ITEM_* -> [RI_*] (normalized)
    half_day_ranges: list[tuple[int, int]] | None = None
    quest_to_ocarina: dict[str, str] | None = None
    quest_item_grants: dict[str, list[str]] | None = None    # QUEST_* -> [RI_*]


def item_display(ctx: EmitContext, ri: str) -> str:
    return ctx.items[ri]["name"]


def canonical_ri_list_for(ri_order: list[str], names: dict[str, str]) -> list[str]:
    """RI ids that become AP items: display-name duplicates collapse to one
    winner (explicit override, else first in enum order), preserving RI order."""
    by_name: dict[str, str] = {}
    for ri in ri_order:
        name = names[ri]
        winner = CANONICAL_NAME_WINNERS.get(name)
        if winner is not None and winner in names:
            by_name[name] = winner
        else:
            by_name.setdefault(name, ri)
    winners = set(by_name.values())
    return [ri for ri in ri_order if ri in winners]


def canonical_ri_list(ctx: EmitContext) -> list[str]:
    return canonical_ri_list_for(ctx.ri_order, {ri: ctx.items[ri]["name"] for ri in ctx.items})


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    print(f"[genlogic] wrote {path.relative_to(path.parents[1])}")


# ---------------------------------------------------------------------------
# Enums.py
# ---------------------------------------------------------------------------

def emit_enums(ctx: EmitContext) -> None:
    lines = [BANNER,
             "# String enums for regions, locations (checks) and items.",
             "# - Locations order mirrors the C++ RandoCheckId enum: the AP location id",
             "#   of the Nth member is N+1, and the game client static_casts AP location",
             "#   ids straight to RandoCheckId. NEVER reorder; regenerate both sides",
             "#   from the same 2ship commit.",
             "# - Items values must exactly match StaticData/Items.cpp names: the game",
             "#   client resolves received items BY NAME.",
             "",
             "from enum import Enum",
             "", ""]

    lines.append("class Regions(str, Enum):")
    for rr in ctx.rr_order:
        key = rr[3:]
        lines.append(f'    {key} = "{ctx.display_name(key)}"')
    lines += ["", ""]

    lines.append("class Locations(str, Enum):")
    for rc in ctx.rc_order:
        key = rc[3:]
        lines.append(f'    {key} = "{ctx.display_name(key)}"')
    lines.append('    VICTORY = "Victory"')
    lines += ["", ""]

    lines.append("class Items(str, Enum):")
    canonical = set(canonical_ri_list(ctx))
    for ri in ctx.ri_order:
        key = ri[3:]
        name = item_display(ctx, ri)
        if ri not in canonical:
            lines.append(f"    # {key} skipped: display name {name!r} belongs to another entry")
            continue
        lines.append(f"    {key} = {name!r}")
    lines.append('    VICTORY = "Victory"')
    lines.append("")

    _write(ctx.apworld_root / "Enums.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# LocationData.py
# ---------------------------------------------------------------------------

def emit_location_data(ctx: EmitContext) -> None:
    lines = [BANNER,
             "# Static per-location data scraped from StaticData/Checks.cpp and",
             "# Logic/PlacementConstraints.cpp.", ""]

    lines.append("# Locations enum key -> C++ RandoCheckType")
    lines.append("LOCATION_RCTYPE: dict[str, str] = {")
    for rc in ctx.rc_order:
        lines.append(f'    "{rc[3:]}": "{ctx.checks[rc]["rctype"]}",')
    lines += ["}", ""]

    lines.append("# Locations enum key -> SCENE_* id")
    lines.append("LOCATION_SCENE: dict[str, str] = {")
    for rc in ctx.rc_order:
        lines.append(f'    "{rc[3:]}": "{ctx.checks[rc]["scene"]}",')
    lines += ["}", ""]

    lines.append("# Locations enum key -> dungeon (only for checks physically inside one),")
    lines.append("# mirroring Rando::Logic::SceneIdToDungeon().")
    lines.append("LOCATION_DUNGEON: dict[str, str] = {")
    for rc in ctx.rc_order:
        dungeon = ctx.scene_to_dungeon.get(ctx.checks[rc]["scene"])
        if dungeon:
            lines.append(f'    "{rc[3:]}": "{dungeon.replace("DUNGEON_SCENE_INDEX_", "")}",')
    lines += ["}", ""]

    _write(ctx.apworld_root / "LocationData.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# VanillaItems.py
# ---------------------------------------------------------------------------

def emit_vanilla_items(ctx: EmitContext) -> None:
    # display-name duplicates collapse to the canonical enum member
    canonical: dict[str, str] = {item_display(ctx, ri): ri[3:] for ri in canonical_ri_list(ctx)}

    lines = [BANNER,
             '"""Vanilla item mapping: which item each check holds in an unshuffled game."""',
             "",
             "from .Enums import Locations, Items",
             "",
             "vanilla_items: dict[Locations, Items] = {"]
    for rc in ctx.rc_order:
        vanilla = ctx.checks[rc]["vanilla"]
        if vanilla in ("RI_UNKNOWN",):
            continue
        if vanilla not in ctx.items:
            raise ValueError(f"{rc}: unknown vanilla item {vanilla}")
        member = canonical[item_display(ctx, vanilla)]
        lines.append(f"    Locations.{rc[3:]}: Items.{member},")
    lines += ["}", ""]

    _write(ctx.apworld_root / "VanillaItems.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# ItemData.py
# ---------------------------------------------------------------------------

def emit_item_data(ctx: EmitContext) -> None:
    lines = [BANNER,
             '"""Static item table scraped from StaticData/Items.cpp.',
             "",
             "AP item ids are permanent once assigned: the generator re-reads this file",
             "and only ever appends new ids. `progression` is computed from the logic:",
             "an item is progression when something the translated rules test for is",
             'granted by it."""',
             "",
             "from typing import NamedTuple",
             "",
             "",
             "class ItemEntry(NamedTuple):",
             "    ap_id: int",
             "    name: str",
             "    ritype: str",
             "    progression: bool",
             "",
             "",
             "ITEMS: dict[str, ItemEntry] = {"]

    for ri in canonical_ri_list(ctx):
        key = ri[3:]
        name = item_display(ctx, ri)
        entry = ctx.items[ri]
        prog = ri in ctx.progression_items
        lines.append(f'    "{key}": ItemEntry({ctx.item_ids[key]}, {name!r}, "{entry["ritype"]}", {prog}),')
    lines += ["}", ""]

    _write(ctx.apworld_root / "ItemData.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# OptionData.py
# ---------------------------------------------------------------------------

def emit_option_data(ctx: EmitContext) -> None:
    lines = [BANNER,
             '"""RO_* option table from StaticData/Options.cpp: (AP option attr, default)."""',
             "",
             "RO_OPTIONS: dict[str, tuple[str, int]] = {"]
    for ro in sorted(ctx.options):
        meta = ctx.options[ro]
        lines.append(f'    "{ro}": ({meta["ap_name"]!r}, {meta["default"]}),')
    lines += ["}", ""]
    _write(ctx.apworld_root / "OptionData.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# LogicHelpersGen.py
# ---------------------------------------------------------------------------

def emit_logic_helpers(ctx: EmitContext) -> None:
    lines = [BANNER,
             '"""Generated logic vocabulary: constants, helper predicates translated from',
             "Logic.h macro bodies, the CanKillEnemy table, and item/flag grant maps",
             'consumed by LogicRuntime."""',
             ""]

    lines.append("# ---- symbolic constants ----------------------------------------------")
    for name in sorted(ctx.constants):
        lines.append(f"{name} = {ctx.constants[name]}")
    lines.append("")

    if ctx.half_day_ranges:
        lines.append("# (start_slice, end_slice) per half-day, from Logic.h HALF_DAY_TIME_RANGES")
        lines.append(f"HALF_DAY_TIME_RANGES = {ctx.half_day_ranges!r}")
        lines.append("")

    lines.append("# ---- helper predicates (from Logic.h / region-local macros) ------------")
    for name in sorted(ctx.helpers):
        lines.append(f"def {name}(s):")
        lines.append(f"    return {ctx.helpers[name]}")
        lines.append("")

    lines.append("# ---- CanKillEnemy ------------------------------------------------------")
    lines.append("CAN_KILL_ENEMY = {")
    for actor in sorted(ctx.can_kill):
        lines.append(f"    {actor!r}: lambda s: {ctx.can_kill[actor]},")
    lines.append("}")
    lines.append("")
    lines.append("def CanKillEnemy(s, actor):")
    lines.append("    if s.opt('RO_SHUFFLE_ENEMY_SOULS') and not s.have_enemy_soul(actor):")
    lines.append("        return False")
    lines.append("    fn = CAN_KILL_ENEMY.get(actor)")
    lines.append("    if fn is None:")
    lines.append("        raise KeyError(f'CanKillEnemy: no logic for {actor}')")
    lines.append("    return fn(s)")
    lines.append("")

    def name_map(title: str, var: str, grants: dict[str, list[str]]) -> None:
        lines.append(f"# ---- {title} ----")
        lines.append(f"{var} = {{")
        for k in sorted(grants):
            names = sorted({item_display(ctx, ri) for ri in grants[k] if ri in ctx.items})
            lines.append(f"    {k!r}: {names!r},")
        lines.append("}")
        lines.append("")

    name_map("RANDO_INF flag -> granting item names", "RANDO_INF_TO_ITEMS", ctx.rando_inf_grants)
    name_map("WEEKEVENTREG -> granting item names", "WEEKEVENTREG_TO_ITEMS", ctx.weekevent_grants)
    if ctx.token_scene_grants:
        name_map("skulltula token scene -> granting item names", "TOKEN_SCENE_TO_ITEMS", ctx.token_scene_grants)
    if ctx.owl_grants:
        name_map("owl warp -> granting item names", "OWL_WARP_TO_ITEMS", ctx.owl_grants)
    if ctx.quest_item_grants:
        name_map("quest item -> granting item names (Item_Give parallel ranges)",
                 "QUEST_TO_ITEMS", ctx.quest_item_grants)

    # ITEM_* -> granting item names (Items.cpp itemId column, ammo packs
    # normalized in the generator so classification and runtime agree)
    name_map("vanilla inventory item -> granting item names", "ITEM_TO_ITEMS", ctx.item_grants or {})

    lines.append("# ---- enemy souls -------------------------------------------------------")
    lines.append("ACTOR_TO_SOUL_ITEM = {")
    for actor in sorted(ctx.soul_map):
        ri = ctx.soul_map[actor]
        if ri in ctx.items:
            lines.append(f"    {actor!r}: {item_display(ctx, ri)!r},")
    lines.append("}")
    lines.append("")

    lines.append("# ---- song note requirements (from Logic.h canPlaySong) ------------------")
    lines.append("SONG_NOTE_REQS = {")
    for song in sorted(ctx.song_note_reqs):
        kind, payload = ctx.song_note_reqs[song]
        lines.append(f"    {song!r}: ({kind!r}, {payload!r}),")
    lines.append("}")
    lines.append("")

    if ctx.quest_to_ocarina:
        lines.append("# QUEST_SONG_* -> OCARINA_SONG_* (offset mapping from the C++ enums)")
        lines.append("QUEST_TO_OCARINA = {")
        for q in sorted(ctx.quest_to_ocarina):
            lines.append(f"    {q!r}: {ctx.quest_to_ocarina[q]!r},")
        lines.append("}")
        lines.append("")

    # dungeon tables
    lines.append("# ---- dungeons ------------------------------------------------------------")
    dungeon_items: dict[str, dict[str, str]] = {}
    for ri, dungeon in ctx.item_to_dungeon.items():
        d = dungeon.replace("DUNGEON_SCENE_INDEX_", "")
        kind = ("small_key" if "SMALL_KEY" in ri else
                "boss_key" if "BOSS_KEY" in ri else
                "stray_fairy" if "STRAY_FAIRY" in ri else None)
        if kind and ri in ctx.items:
            dungeon_items.setdefault(d, {})[kind] = item_display(ctx, ri)
    lines.append("DUNGEON_ITEMS = {")
    for d in sorted(dungeon_items):
        lines.append(f"    {d!r}: {dungeon_items[d]!r},")
    lines.append("}")
    lines.append("")

    # moon masks (ITEM_MASK_TRUTH..ITEM_MASK_GIANT)
    item_enum = {n: v for n, v in ctx.enums.get("ItemId", [])}
    lo, hi = item_enum.get("ITEM_MASK_TRUTH"), item_enum.get("ITEM_MASK_GIANT")
    moon_masks: list[str] = []
    if lo is not None and hi is not None:
        for ri in ctx.ri_order:
            v = item_enum.get(ctx.items[ri]["item_id"])
            if v is not None and lo <= v <= hi:
                moon_masks.append(item_display(ctx, ri))
    lines.append("# Masks counted by MoonMaskCount() (ITEM_MASK_TRUTH..ITEM_MASK_GIANT)")
    lines.append(f"MOON_MASK_ITEMS = {sorted(set(moon_masks))!r}")
    lines.append("")

    remains = [item_display(ctx, ri) for ri in ctx.ri_order if ri.startswith("RI_REMAINS_")]
    lines.append(f"REMAINS_ITEMS = {remains!r}")
    lines.append("")

    bottles = [item_display(ctx, ri) for ri in ctx.ri_order if ri.startswith("RI_BOTTLE_")]
    lines.append(f"BOTTLE_ITEMS = {bottles!r}")
    lines.append("")

    _write(ctx.apworld_root / "LogicHelpersGen.py", "\n".join(lines))


# ---------------------------------------------------------------------------
# RegionData.py
# ---------------------------------------------------------------------------

def emit_region_data(ctx: EmitContext) -> None:
    lines = [BANNER,
             '"""The translated region graph: checks, connections, exits, events and',
             "time-stay restrictions per region, with access rules as lambdas over a",
             'LogicContext `s` (see LogicRuntime).  Original C++ conditions are kept',
             'alongside each rule for debugging."""',
             "",
             "from typing import NamedTuple",
             "",
             "from .LogicHelpersGen import *  # noqa: F401,F403 — constants + helpers",
             "",
             "",
             "class RegionSpec(NamedTuple):",
             "    scene: str",
             "    can_stay: bool",
             "    checks: tuple          # (RC key, rule, cpp_source)",
             "    connections: tuple     # (RR key, rule, cpp_source)",
             "    exits: tuple           # (RR key, (scene, spawn), rule, cpp_source)",
             "    events: tuple          # (RE key, rule, cpp_source)",
             "    stays: tuple           # (time_slice, rule, cpp_source)",
             "",
             "",
             'START_REGION = "RR_MAX"',
             "",
             "REGIONS: dict[str, RegionSpec] = {"]

    def fmt_cond(py: str, cond: str) -> tuple[str, str]:
        src = " ".join(cond.split())
        if len(src) > 160:
            src = src[:157] + "..."
        return py, src

    for rid in sorted(ctx.translated_regions):
        t = ctx.translated_regions[rid]
        lines.append(f"    {rid!r}: RegionSpec(")
        lines.append(f"        scene={t['scene']!r},")
        lines.append(f"        can_stay={t['can_stay']},")

        lines.append("        checks=(")
        for rc, py, cond in t["checks"]:
            py, src = fmt_cond(py, cond)
            lines.append(f"            ({rc!r}, lambda s: {py}, {src!r}),")
        lines.append("        ),")

        lines.append("        connections=(")
        for target, py, cond in t["connections"]:
            py, src = fmt_cond(py, cond)
            lines.append(f"            ({target!r}, lambda s: {py}, {src!r}),")
        lines.append("        ),")

        lines.append("        exits=(")
        for target, ent, py, cond in t["exits"]:
            py, src = fmt_cond(py, cond)
            lines.append(f"            ({target!r}, {ent!r}, lambda s: {py}, {src!r}),")
        lines.append("        ),")

        lines.append("        events=(")
        for ev, py, cond in t["events"]:
            py, src = fmt_cond(py, cond)
            lines.append(f"            ({ev!r}, lambda s: {py}, {src!r}),")
        lines.append("        ),")

        lines.append("        stays=(")
        for slice_name, py, cond in t["stays"]:
            py, src = fmt_cond(py, cond)
            lines.append(f"            ({slice_name}, lambda s: {py}, {src!r}),")
        lines.append("        ),")
        lines.append("    ),")
    lines += ["}", ""]

    _write(ctx.apworld_root / "RegionData.py", "\n".join(lines))


# ---------------------------------------------------------------------------

def emit_all(ctx: EmitContext) -> None:
    emit_enums(ctx)
    emit_location_data(ctx)
    emit_vanilla_items(ctx)
    emit_item_data(ctx)
    emit_option_data(ctx)
    emit_logic_helpers(ctx)
    emit_region_data(ctx)
